### ISSUE TITLE
Allure for Bamboo plugin generates empty allure report

### ISSUE THREAD

**Issue by robertgates55** [allure-framework/allure-bamboo#31] opened 2017-09-22 11:22 UTC
I've just switched from the Allure-Plugin to Allure-for-Bamboo, and believe I have the plugin configured correctly - building a report using the 'Allure Report' task as part of a build job, and pointing the plugin at my 'allure-results/' directory, I see the report I'm expecting is generated as I'm expecting (which I can then host as an artefact)

However, I believe that by enabling Plan Configuration > Miscellaneous > Allure Reporting > Enable Allure Building, the report should be automatically built and added as a new tab once the job completes. 

In my case, my allure-results folder is at ${bamboo.working.directory}/allure-results. After successfully completing a run, I do get the 'Allure Report' tab, however it contains 0 test results.

**Comment by smecsia** [comment] 2017-09-22 11:30
@robertgates55 please refer the "Troubleshooting" section of the [docs](https://docs.qameta.io/allure/latest/#_bamboo). Empty report tab most might mean that you haven't configured the directory for the generated Allure reports correctly. Usually it means that report has been removed after the generation. 

Please check the configured directory and see what files you have there.

**Comment by smecsia** [comment] 2017-09-22 11:40
Sorry, I probably misunderstood your problem. So you actually have the report, but it does not contain the tests, right?

**Comment by robertgates55** [comment] 2017-09-22 11:42
I checked the 'troubleshooting' docs, but my scenario is none of those - I get a report generated, but the report itself has no test results:
![image](https://user-images.githubusercontent.com/7437497/30742873-291def9e-9f93-11e7-978b-1f852ede9575.png)

Using the allure report task to build a report from my allure-results folder however, I get a report with 10 test cases generated, as expected.

How do I configure the directory to look in? How can I tell what directory the allure plugin is looking for/building a report from?
![image](https://user-images.githubusercontent.com/7437497/30742798-c3f9a202-9f92-11e7-8e66-499840d0fd90.png)

**Comment by smecsia** [comment] 2017-09-22 12:10
@robertgates55 Thanks for the explanation. In your case you actually have the built report, which is good, so the report storage directory is configured correctly. I assume that something is wrong with the allure artifacts that are produced by the job. 
1. Please check the built artifacts for your job and make sure that you have the Allure results correctly generated by the job.
2. Please refer to the Bamboo server logs and find the lines that contain `AllureBuildCompleteAction`. This might help you to debug the process of Allure report generation. And post them here if possible.
3. Also indicate the Allure adaptor that you're actually using for collecting of the test results.

**Comment by robertgates55** [comment] 2017-09-22 13:16
Thanks.

I wasn't aware that build artifacts need to be produced by the job - do I need to define those in the job configuration? Obviously the job is writing allure results into  ${bamboo.working.directory}/allure-results - do I need to create a bamboo artifact to collect these? What artifact name does it need for the allure report to be built from those results?

I'm using the rspec adaptor - I've confirmed that allure will build a report (with 10 test cases!) with these results.

**Comment by smecsia** [comment] 2017-09-22 13:41
@robertgates55 AFAIU all you need is to define an artifact with the following pattern "**/allure-results". 
The name of the artifact does not matter. Allure plugin downloads all the artifacts that are produced by the job and finds the Allure results in them.

**Comment by robertgates55** [comment] 2017-09-22 17:00
I am definitely creating a shared artifact that contains the allure-results directory (with results xmls inside), but sadly the allure report that is being generated still contains 0 test cases.

![image](https://user-images.githubusercontent.com/7437497/30755646-634eb118-9fbf-11e7-9f31-5b8a692916ea.png)

![image](https://user-images.githubusercontent.com/7437497/30755620-52c9bf90-9fbf-11e7-9801-e7f9f784656d.png)

Has anyone had this working? Has it been tested with bamboo agents, or perhaps only with a shared server/agent on a single box?

**Comment by smecsia** [comment] 2017-09-22 23:25
We're actually using this plugin at Atlassian internally. 
Have you checked the Bamboo server logs as I suggested?
Please indicate the following: 
- version of Bamboo server
- version of Allure Report builder
- version of allure-rspec
- version of Allure Report builder command line which you were using to test that a report is correctly generated

Also please note that allure-rspec currently generates results in the old (1.x) Allure format, whereas this Bamboo plugin uses the new (2.x) builder command line. This might be also the cause of your issue.

**Comment by robertgates55** [comment] 2017-09-27 12:43
Turns out this was becuase the artifact wasn't defined in the correct way.

I can confirm that the following artifact config has resolved the issue for me:

![image](https://user-images.githubusercontent.com/7437497/30913909-b63c6e7e-a389-11e7-8af5-357fdd7f2eaa.png)

**Comment by smecsia** [comment] 2017-09-27 12:48
@robertgates55 good to know, thanks. I'm closing this then. 
The new docs will contain the info about the artifact configuration.

**Closed** 2017-09-27 12:52 UTC
